
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: paciorky_development
  pool: 5
  username: paciorky
  password: paciorky
  host: localhost

test:
  adapter: mysql2
  database: paciorky_test
  encoding: utf8
  reconnect: false
  database: paciorky_development
  username: paciorky
  password: paciorky
  pool: 5
  host: localhost